<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\..\RhinoProjectPropertySheets\Rhino.CS.Dll.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <EnableDefaultItems>false</EnableDefaultItems>
    <FileAlignment>512</FileAlignment>
    <WarningLevel>4</WarningLevel>
    <GenerateResourceUsePreserializedResources>True</GenerateResourceUsePreserializedResources>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>$(RhinoBinDir)\$(Configuration)\Plug-ins\</OutputPath>
    <DefineConstants Condition="'$(OS)' == 'Windows_NT'">ON_RUNTIME_WIN;TRACE;DEBUG;</DefineConstants>
    <DefineConstants Condition="'$(OS)' != 'Windows_NT'">TRACE;DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>anycpu</PlatformTarget>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>$(RhinoBinDir)\$(Configuration)\Plug-ins\</OutputPath>
    <DefineConstants Condition="'$(OS)' == 'Windows_NT'">ON_RUNTIME_WIN;TRACE;</DefineConstants>
    <DefineConstants Condition="'$(OS)' != 'Windows_NT'">TRACE;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\version.cs" Link="Properties\version.cs" />
    <Compile Include="KHR_draco_mesh_compression.cs" />
    <Compile Include="KHR_materials_clearcoat.cs" />
    <Compile Include="KHR_materials_ior.cs" />
    <Compile Include="KHR_materials_specular.cs" />
    <Compile Include="KHR_materials_transmission.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\glTFLoader\glTFLoader.csproj" />
  </ItemGroup>
</Project>
