<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RhinoVersion>7</RhinoVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <!-- change for 7, 8 etc. -->
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks Condition=" '$(RhinoVersion)'=='8' "> net7.0-windows</TargetFrameworks>
    <Version>1.0</Version>
    <Title>ExportglTF_SHoP</Title>
    <Description>Custom GglTF exporter by SHoP</Description>
    <TargetExt>.rhp</TargetExt>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  <PropertyGroup>

    <TargetFrameworks Condition=" '$(RhinoVersion)'=='7' "> net48-windows</TargetFrameworks>
    <Version>1.0</Version>
    <Title>ExportglTF_SHoP</Title>
    <Description>Custom glTF exporter by SHoP</Description>
    <TargetExt>.rhp</TargetExt>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\glTF-BinExporter\Constants.cs" Link="Constants.cs" />
    <Compile Include="..\..\glTF-BinExporter\glTFBinExporterPlugin.cs" Link="glTFBinExporterPlugin.cs" />
    <Compile Include="..\..\glTF-BinExporter\glTFExportOptions.cs" Link="glTFExportOptions.cs" />
    <Compile Include="..\..\glTF-BinExporter\glTFExportOptionsDialog.cs" Link="glTFExportOptionsDialog.cs" />
    <Compile Include="..\..\glTF-BinExporter\gltfSchemaDummy.cs" Link="gltfSchemaDummy.cs" />
    <Compile Include="..\..\glTF-BinExporter\gltfSchemaSceneDummy.cs" Link="gltfSchemaSceneDummy.cs" />
    <Compile Include="..\..\glTF-BinExporter\GlTFUtils.cs" Link="GlTFUtils.cs" />
    <Compile Include="..\..\glTF-BinExporter\RhinoDocGltfConverter.cs" Link="RhinoDocGltfConverter.cs" />
    <Compile Include="..\..\glTF-BinExporter\RhinoMaterialGltfConverter.cs" Link="RhinoMaterialGltfConverter.cs" />
    <Compile Include="..\..\glTF-BinExporter\RhinoMeshGltfConverter.cs" Link="RhinoMeshGltfConverter.cs" />
    <Compile Include="..\..\glTF-BinExporter\RhinoPointCloudGltfConverter.cs" Link="RhinoPointCloudGltfConverter.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="glTF2Loader" Version="1.1.4-alpha" />
    <PackageReference Condition=" '$(RhinoVersion)'=='8' " Include="RhinoCommon" Version="8.15.25019.13001" IncludeAssets="compile;build" />
    <PackageReference Condition=" '$(RhinoVersion)'=='7' " Include="RhinoCommon" Version="7.37.24107.15001" IncludeAssets="compile;build" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\glTFExtension_SHoP\glTFExtension_SHoP.csproj" />
  </ItemGroup>
  
  <PropertyGroup Condition="$(Configuration) == 'Debug' AND $([MSBuild]::IsOSPlatform(Windows))">
    <StartProgram>C:\Program Files\Rhino 7\System\Rhino.exe</StartProgram>
    <StartArguments></StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>
  
</Project>