<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RhinoVersion>7</RhinoVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <!-- change for 7, 8 etc. -->
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks Condition=" '$(RhinoVersion)'=='8' "> net7.0-windows</TargetFrameworks>
    <Version>0.1.8</Version>
    <Title>ImportglTF_SHoP</Title>
    <Description>Custom glTF importer by SHoP</Description>
    <TargetExt>.rhp</TargetExt>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  <PropertyGroup>

    <TargetFrameworks Condition=" '$(RhinoVersion)'=='7' "> net48-windows</TargetFrameworks>
    <Version>0.1.8</Version>
    <Title>ImportglTF_SHoP</Title>
    <Description>Custom glTF importer by SHoP</Description>
    <TargetExt>.rhp</TargetExt>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\glTF-BinImporter\glTFBinImporterPlugIn.cs" Link="glTFBinImporterPlugIn.cs" />
    <Compile Include="..\..\glTF-BinImporter\GltfRhinoConverter.cs" Link="GltfRhinoConverter.cs" />
    <Compile Include="..\..\glTF-BinImporter\GltfRhinoMaterialConverter.cs" Link="GltfRhinoMaterialConverter.cs" />
    <Compile Include="..\..\glTF-BinImporter\GltfRhinoMeshConverter.cs" Link="GltfRhinoMeshConverter.cs" />
    <Compile Include="..\..\glTF-BinImporter\GltfUtils.cs" Link="GltfUtils.cs" />
    <Compile Include="..\..\glTF-BinImporter\RhinoGltfMetallicRoughnessConverter.cs" Link="RhinoGltfMetallicRoughnessConverter.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Condition=" '$(RhinoVersion)'=='8' " Include="RhinoCommon" Version="8.23.25251.13001" IncludeAssets="compile;build" />
    <PackageReference Condition=" '$(RhinoVersion)'=='7' " Include="RhinoCommon" Version="7.37.24107.15001" IncludeAssets="compile;build" />
    <PackageReference Include="glTF2Loader" Version="1.1.4-alpha" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\glTFExtension_SHoP\glTFExtension_SHoP.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="$(Configuration) == 'Debug' AND $([MSBuild]::IsOSPlatform(Windows)) AND '$(RhinoVersion)'=='7'">
    <StartProgram>C:\Program Files\Rhino 7\System\Rhino.exe</StartProgram>
    <StartArguments></StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Debug' AND $([MSBuild]::IsOSPlatform(Windows)) AND '$(RhinoVersion)'=='8'">
    <StartProgram>C:\Program Files\Rhino 8\System\Rhino.exe</StartProgram>
    <StartArguments></StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
	</PropertyGroup>
  
</Project>